# Generated by Django 4.0.4 on 2022-05-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_band'),
    ]

    operations = [
        migrations.RenameField(
            model_name='band',
            old_name='year_formed',
            new_name='start_year',
        ),
        migrations.RemoveField(
            model_name='band',
            name='active',
        ),
        migrations.RemoveField(
            model_name='band',
            name='biography',
        ),
        migrations.RemoveField(
            model_name='band',
            name='official_homepage',
        ),
        migrations.AddField(
            model_name='band',
            name='inflation',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='band',
            name='revenues',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
    ]
