# Generated by Django 4.0.4 on 2022-05-27 16:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_rename_year_formed_band_start_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='length',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='band',
            name='periodicity',
            field=models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='band',
            name='genre',
            field=models.CharField(choices=[('Wind', 'Wind'), ('Solar', 'Solar'), ('Road', 'Road')], max_length=5),
        ),
        migrations.AlterField(
            model_name='band',
            name='inflation',
            field=models.FloatField(),
        ),
    ]
