# Generated by Django 4.0.4 on 2022-05-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_band_length_band_periodicity_alter_band_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='opex',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
    ]
