# Generated by Django 4.0.4 on 2022-05-29 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_band_opex'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='band',
            new_name='Project',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='band',
            new_name='project',
        ),
    ]
