# Generated by Django 4.0.4 on 2022-06-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_rename_band_project_rename_band_listing_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='start_year',
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=0.001281415343915344),
            preserve_default=False,
        ),
    ]
