# Generated by Django 4.0.4 on 2022-06-06 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_alter_project_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='start_date',
            new_name='start_year',
        ),
    ]
