# Generated by Django 4.0.4 on 2022-06-06 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_rename_start_date_project_start_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='start_year',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
