# Generated by Django 4.0.4 on 2022-06-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_alter_project_start_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='start_year',
            field=models.DateField(),
        ),
    ]
