# Generated by Django 4.0.4 on 2022-06-06 12:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_alter_project_start_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='start_year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3000)]),
        ),
    ]
