# Generated by Django 4.0.4 on 2022-06-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_project_opex1_project_opex2_project_opex3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='opex90',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
