# Generated by Django 4.0.4 on 2022-06-17 18:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('Wind', 'Wind'), ('Solar', 'Solar'), ('Road', 'Road')], max_length=5)),
                ('start_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3000)])),
                ('length', models.IntegerField()),
                ('periodicity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('revenues', models.IntegerField()),
                ('inflation', models.FloatField()),
                ('opex', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='webApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webApp.project')),
            ],
        ),
    ]
