# Generated by Django 4.2 on 2025-08-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_model', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='cfe_commune_tax',
        ),
        migrations.RemoveField(
            model_name='project',
            name='cfe_discount_tax_base',
        ),
        migrations.RemoveField(
            model_name='project',
            name='cfe_discount_tax_base_y1',
        ),
        migrations.RemoveField(
            model_name='project',
            name='cfe_instal_q1',
        ),
        migrations.RemoveField(
            model_name='project',
            name='cfe_instal_q2',
        ),
        migrations.RemoveField(
            model_name='project',
            name='cfe_instal_q3',
        ),
        migrations.RemoveField(
            model_name='project',
            name='cfe_instal_q4',
        ),
        migrations.RemoveField(
            model_name='project',
            name='cfe_intercommunal_tax',
        ),
        migrations.RemoveField(
            model_name='project',
            name='cfe_localCCI_tax',
        ),
        migrations.RemoveField(
            model_name='project',
            name='cfe_mgt_fee',
        ),
        migrations.RemoveField(
            model_name='project',
            name='cfe_specific_eqp_tax',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tfpb_additional_tax',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tfpb_commune_tax',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tfpb_department_tax',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tfpb_region_tax',
        ),
        migrations.AlterField(
            model_name='project',
            name='valuation',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
