# Generated by Django 4.2 on 2024-08-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialmodel',
            name='project_status',
            field=models.CharField(default='Development', max_length=25),
        ),
    ]
