# Generated by Django 4.2 on 2024-08-13 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_model', '0002_financialmodel_project_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialmodel',
            name='project_status',
        ),
    ]
