# Generated by Django 4.2 on 2025-08-11 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_model', '0002_remove_project_cfe_commune_tax_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='calculation_detail',
        ),
        migrations.RemoveField(
            model_name='project',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='project',
            name='debt_negative_tail',
        ),
        migrations.RemoveField(
            model_name='project',
            name='debt_reference_rate_buffer',
        ),
        migrations.RemoveField(
            model_name='project',
            name='debt_swap_margin',
        ),
        migrations.RemoveField(
            model_name='project',
            name='debt_swap_rate',
        ),
        migrations.RemoveField(
            model_name='project',
            name='initial_wc',
        ),
        migrations.RemoveField(
            model_name='project',
            name='rotor_diameter',
        ),
        migrations.RemoveField(
            model_name='project',
            name='timeline_quarters_ceiling',
        ),
    ]
