# Generated by Django 4.2 on 2024-08-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_model', '0003_remove_financialmodel_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialmodel',
            name='IRR',
            field=models.FloatField(default=10.0),
        ),
    ]
