# Generated by Django 4.2 on 2025-08-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_model', '0003_remove_project_calculation_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='archeological_tax',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.4, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='archeological_tax_base_solar',
            field=models.DecimalField(blank=True, decimal_places=2, default=10, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='dev_tax_taxable_base_solar',
            field=models.DecimalField(blank=True, decimal_places=2, default=10, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='dev_tax_taxable_base_wind',
            field=models.DecimalField(blank=True, decimal_places=2, default=3000, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='panels_surface',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
