# Generated by Django 4.2 on 2024-08-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_model', '0004_financialmodel_irr'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialmodel',
            name='valuation',
            field=models.FloatField(default=1000.0),
        ),
    ]
