# Generated by Django 4.2 on 2025-08-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_model', '0004_alter_project_archeological_tax_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='financialmodel',
            index=models.Index(fields=['project', 'identifier'], name='fm_project_identifier_idx'),
        ),
        migrations.AddIndex(
            model_name='financialmodel',
            index=models.Index(fields=['project', 'model_type'], name='fm_project_model_type_idx'),
        ),
        migrations.AddIndex(
            model_name='financialmodel',
            index=models.Index(fields=['project'], name='fm_project_idx'),
        ),
        migrations.AddIndex(
            model_name='financialmodel',
            index=models.Index(fields=['identifier'], name='fm_identifier_idx'),
        ),
        migrations.AddIndex(
            model_name='financialmodel',
            index=models.Index(fields=['depends_on'], name='fm_depends_on_idx'),
        ),
        migrations.AddConstraint(
            model_name='financialmodel',
            constraint=models.UniqueConstraint(fields=('project', 'identifier'), name='unique_project_identifier'),
        ),
    ]
