# Generated by Django 4.2 on 2025-08-12 19:43

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_model', '0005_financialmodel_fm_project_identifier_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='financialmodel',
            name='fm_project_model_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='financialmodel',
            name='fm_project_idx',
        ),
        migrations.RemoveIndex(
            model_name='financialmodel',
            name='fm_identifier_idx',
        ),
        migrations.RemoveIndex(
            model_name='financialmodel',
            name='fm_depends_on_idx',
        ),
        migrations.AddIndex(
            model_name='financialmodel',
            index=django.contrib.postgres.indexes.GinIndex(fields=['financial_model'], name='fm_financial_model_gin_idx'),
        ),
    ]
