# Generated by Django 4.2 on 2025-01-07 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial_model', '0006_debtdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtdata',
            name='financial_model',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recorded_results', to='financial_model.financialmodel'),
        ),
        migrations.AddField(
            model_name='financialmodel',
            name='depends_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_models', to='financial_model.financialmodel'),
        ),
    ]
