# Generated by Django 4.2 on 2025-01-07 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_model', '0007_debtdata_financial_model_financialmodel_depends_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='P99_10y',
        ),
    ]
