# Generated by Django 4.2 on 2025-03-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_model', '0008_remove_project_p99_10y'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sensi_inflation_sponsor',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=3),
        ),
        migrations.AddField(
            model_name='project',
            name='sensi_opex_sponsor',
            field=models.DecimalField(decimal_places=0, default=10, max_digits=3),
        ),
        migrations.AddField(
            model_name='project',
            name='sensi_production_sponsor',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
        ),
    ]
