# Generated by Django 4.2 on 2025-04-02 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_model', '0011_project_sponsor_irr'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='valuation',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4),
        ),
    ]
