# Generated by Django 4.2 on 2025-07-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_model', '0012_project_valuation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='sponsor_irr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='DebtData',
        ),
    ]
