# Generated by Django 4.0.4 on 2022-07-16 15:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('Wind', 'Wind'), ('Solar', 'Solar'), ('Road', 'Road')], max_length=5)),
                ('country', models.CharField(max_length=20)),
                ('start_construction', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('end_construction', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('operating_life', models.IntegerField(default='20')),
                ('periodicity', models.IntegerField(default='3')),
                ('panels_capacity', models.IntegerField(default='2000')),
                ('annual_degradation', models.DecimalField(decimal_places=0, default=2, max_digits=4)),
                ('p50', models.IntegerField(default='2000')),
                ('p90_10y', models.IntegerField(default='2000')),
                ('P99_10y', models.IntegerField(default='2000')),
                ('availability', models.DecimalField(decimal_places=0, default=0, max_digits=4)),
                ('seasonality_m1', models.DecimalField(decimal_places=0, default=0, max_digits=4)),
                ('seasonality_m2', models.DecimalField(decimal_places=0, default=0, max_digits=4)),
                ('seasonality_m3', models.DecimalField(decimal_places=0, default=0, max_digits=4)),
                ('seasonality_m4', models.DecimalField(decimal_places=0, default=0, max_digits=4)),
                ('seasonality_m5', models.DecimalField(decimal_places=0, default=0, max_digits=4)),
                ('seasonality_m6', models.DecimalField(decimal_places=0, default=0, max_digits=4)),
                ('seasonality_m7', models.DecimalField(decimal_places=0, default=0, max_digits=4)),
                ('seasonality_m8', models.DecimalField(decimal_places=0, default=0, max_digits=4)),
                ('seasonality_m9', models.DecimalField(decimal_places=0, default=0, max_digits=4)),
                ('seasonality_m10', models.DecimalField(decimal_places=0, default=0, max_digits=4)),
                ('seasonality_m11', models.DecimalField(decimal_places=0, default=0, max_digits=4)),
                ('seasonality_m12', models.DecimalField(decimal_places=0, default=0, max_digits=4)),
                ('costs_at_NTP', models.IntegerField(default='0')),
                ('costs_at_FC', models.IntegerField(default='0')),
                ('costs_at_COD', models.IntegerField(default='0')),
                ('costs_m1', models.IntegerField(default='0')),
                ('costs_m2', models.IntegerField(default='0')),
                ('costs_m3', models.IntegerField(default='0')),
                ('costs_m4', models.IntegerField(default='0')),
                ('costs_m5', models.IntegerField(default='0')),
                ('costs_m6', models.IntegerField(default='0')),
                ('costs_m7', models.IntegerField(default='0')),
                ('costs_m8', models.IntegerField(default='0')),
                ('costs_m9', models.IntegerField(default='0')),
                ('costs_m10', models.IntegerField(default='0')),
                ('costs_m11', models.IntegerField(default='0')),
                ('costs_m12', models.IntegerField(default='0')),
                ('revenues', models.IntegerField()),
                ('inflation', models.FloatField()),
                ('opex', models.IntegerField()),
            ],
        ),
    ]
