# Generated by Django 4.2 on 2024-06-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxPost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='computationresult',
            name='dashboard_tables',
            field=models.JSONField(default=dict),
        ),
    ]
