# Generated by Django 4.2 on 2023-05-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxPost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='liquidation',
            field=models.IntegerField(default='6'),
        ),
    ]
