# Generated by Django 4.0.4 on 2022-09-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxPost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='devfee_choice',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='project',
            name='devfee_paid_COD',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4),
        ),
        migrations.AddField(
            model_name='project',
            name='devfee_paid_FC',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='project',
            name='costs_m2',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='project',
            name='costs_m3',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='project',
            name='opex',
            field=models.IntegerField(default='100'),
        ),
    ]
