# Generated by Django 4.2 on 2023-06-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxPost', '0002_project_liquidation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='availability',
        ),
        migrations.AddField(
            model_name='project',
            name='injection_choice',
            field=models.IntegerField(default='1'),
        ),
    ]
