# Generated by Django 4.2 on 2023-06-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxPost', '0003_remove_project_availability_project_injection_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='SHL_margin',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=4),
        ),
        migrations.AddField(
            model_name='project',
            name='subgearing',
            field=models.DecimalField(decimal_places=2, default=90, max_digits=4),
        ),
    ]
