# Generated by Django 4.0.4 on 2022-07-17 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxPost', '0003_sproject_p99_10y_sproject_annual_degradation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sproject',
            name='P99_10y',
        ),
        migrations.RemoveField(
            model_name='sproject',
            name='annual_degradation',
        ),
        migrations.RemoveField(
            model_name='sproject',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='sproject',
            name='p50',
        ),
        migrations.RemoveField(
            model_name='sproject',
            name='p90_10y',
        ),
        migrations.RemoveField(
            model_name='sproject',
            name='seasonality_m1',
        ),
        migrations.RemoveField(
            model_name='sproject',
            name='seasonality_m10',
        ),
        migrations.RemoveField(
            model_name='sproject',
            name='seasonality_m11',
        ),
        migrations.RemoveField(
            model_name='sproject',
            name='seasonality_m12',
        ),
        migrations.RemoveField(
            model_name='sproject',
            name='seasonality_m2',
        ),
        migrations.RemoveField(
            model_name='sproject',
            name='seasonality_m3',
        ),
        migrations.RemoveField(
            model_name='sproject',
            name='seasonality_m4',
        ),
        migrations.RemoveField(
            model_name='sproject',
            name='seasonality_m5',
        ),
        migrations.RemoveField(
            model_name='sproject',
            name='seasonality_m6',
        ),
        migrations.RemoveField(
            model_name='sproject',
            name='seasonality_m7',
        ),
        migrations.RemoveField(
            model_name='sproject',
            name='seasonality_m8',
        ),
        migrations.RemoveField(
            model_name='sproject',
            name='seasonality_m9',
        ),
    ]
