# Generated by Django 4.0.4 on 2022-07-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxPost', '0005_sproject_p99_10y_sproject_annual_degradation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sproject',
            name='seasonality_m1',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
    ]
