# Generated by Django 4.2 on 2023-07-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxPost', '0005_project_calculation_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='payment_delay_costs',
            field=models.IntegerField(default='30'),
        ),
        migrations.AddField(
            model_name='project',
            name='payment_delay_revenues',
            field=models.IntegerField(default='30'),
        ),
    ]
