# Generated by Django 4.0.4 on 2022-06-26 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxPost', '0005_contact_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='message',
        ),
    ]
