# Generated by Django 4.2 on 2023-07-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxPost', '0006_project_payment_delay_costs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='DSRA_choice',
            field=models.IntegerField(default='1'),
        ),
    ]
