# Generated by Django 4.0.4 on 2022-07-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxPost', '0006_alter_sproject_seasonality_m1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sproject',
            name='annual_degradation',
            field=models.DecimalField(decimal_places=0, default=0.04, max_digits=5),
        ),
        migrations.AlterField(
            model_name='sproject',
            name='availability',
            field=models.DecimalField(decimal_places=0, default=0.99, max_digits=4),
        ),
        migrations.AlterField(
            model_name='sproject',
            name='seasonality_m1',
            field=models.DecimalField(decimal_places=3, default=0.03, max_digits=5),
        ),
        migrations.AlterField(
            model_name='sproject',
            name='seasonality_m10',
            field=models.DecimalField(decimal_places=0, default=0.06, max_digits=5),
        ),
        migrations.AlterField(
            model_name='sproject',
            name='seasonality_m11',
            field=models.DecimalField(decimal_places=0, default=0.03, max_digits=5),
        ),
        migrations.AlterField(
            model_name='sproject',
            name='seasonality_m12',
            field=models.DecimalField(decimal_places=0, default=0.02, max_digits=5),
        ),
        migrations.AlterField(
            model_name='sproject',
            name='seasonality_m2',
            field=models.DecimalField(decimal_places=0, default=0.05, max_digits=5),
        ),
        migrations.AlterField(
            model_name='sproject',
            name='seasonality_m3',
            field=models.DecimalField(decimal_places=0, default=0.09, max_digits=5),
        ),
        migrations.AlterField(
            model_name='sproject',
            name='seasonality_m4',
            field=models.DecimalField(decimal_places=0, default=0.11, max_digits=5),
        ),
        migrations.AlterField(
            model_name='sproject',
            name='seasonality_m5',
            field=models.DecimalField(decimal_places=0, default=0.13, max_digits=5),
        ),
        migrations.AlterField(
            model_name='sproject',
            name='seasonality_m6',
            field=models.DecimalField(decimal_places=0, default=0.13, max_digits=5),
        ),
        migrations.AlterField(
            model_name='sproject',
            name='seasonality_m7',
            field=models.DecimalField(decimal_places=0, default=0.13, max_digits=5),
        ),
        migrations.AlterField(
            model_name='sproject',
            name='seasonality_m8',
            field=models.DecimalField(decimal_places=0, default=0.12, max_digits=5),
        ),
        migrations.AlterField(
            model_name='sproject',
            name='seasonality_m9',
            field=models.DecimalField(decimal_places=0, default=0.1, max_digits=5),
        ),
    ]
