# Generated by Django 4.0.4 on 2022-06-27 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxPost', '0006_remove_contact_email_remove_contact_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='SProject',
        ),
    ]
