# Generated by Django 4.0.4 on 2022-06-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxPost', '0007_rename_contact_sproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='sproject',
            name='revenues',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
    ]
