# Generated by Django 4.2 on 2023-07-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxPost', '0007_project_dsra_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cash_min',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='project',
            name='initial_wc',
            field=models.IntegerField(default='1'),
        ),
    ]
