# Generated by Django 4.0.4 on 2022-06-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxPost', '0008_sproject_revenues'),
    ]

    operations = [
        migrations.AddField(
            model_name='sproject',
            name='opex',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
    ]
