# Generated by Django 4.0.4 on 2022-07-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxPost', '0008_remove_sproject_inflation_remove_sproject_revenues_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sproject',
            name='periodicity',
            field=models.IntegerField(choices=[('3', 'Quarterly'), ('6', 'Semi-annual')], default='3'),
        ),
    ]
