# Generated by Django 4.2 on 2023-07-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxPost', '0008_project_cash_min_project_initial_wc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='costs_m1',
        ),
        migrations.RemoveField(
            model_name='project',
            name='costs_m10',
        ),
        migrations.RemoveField(
            model_name='project',
            name='costs_m11',
        ),
        migrations.RemoveField(
            model_name='project',
            name='costs_m12',
        ),
        migrations.RemoveField(
            model_name='project',
            name='costs_m2',
        ),
        migrations.RemoveField(
            model_name='project',
            name='costs_m3',
        ),
        migrations.RemoveField(
            model_name='project',
            name='costs_m4',
        ),
        migrations.RemoveField(
            model_name='project',
            name='costs_m5',
        ),
        migrations.RemoveField(
            model_name='project',
            name='costs_m6',
        ),
        migrations.RemoveField(
            model_name='project',
            name='costs_m7',
        ),
        migrations.RemoveField(
            model_name='project',
            name='costs_m8',
        ),
        migrations.RemoveField(
            model_name='project',
            name='costs_m9',
        ),
        migrations.AlterField(
            model_name='project',
            name='calculation_detail',
            field=models.IntegerField(default='2'),
        ),
    ]
