# Generated by Django 4.0.4 on 2022-07-02 19:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxPost', '0009_sproject_opex'),
    ]

    operations = [
        migrations.AddField(
            model_name='sproject',
            name='country',
            field=models.CharField(default='France', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sproject',
            name='genre',
            field=models.CharField(choices=[('Wind', 'Wind'), ('Solar', 'Solar'), ('Road', 'Road')], default='Wind', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sproject',
            name='inflation',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sproject',
            name='length',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sproject',
            name='periodicity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sproject',
            name='start_year',
            field=models.IntegerField(default=2000, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3000)]),
            preserve_default=False,
        ),
    ]
