# Generated by Django 4.0.4 on 2022-07-13 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxPost', '0010_sproject_country_sproject_genre_sproject_inflation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sproject',
            name='costs_at_FC',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='sproject',
            name='costs_at_NTP',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='sproject',
            name='costs_month_1',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='sproject',
            name='costs_month_10',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='sproject',
            name='costs_month_11',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='sproject',
            name='costs_month_12',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='sproject',
            name='costs_month_2',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='sproject',
            name='costs_month_3',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='sproject',
            name='costs_month_4',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='sproject',
            name='costs_month_5',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='sproject',
            name='costs_month_6',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='sproject',
            name='costs_month_7',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='sproject',
            name='costs_month_8',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='sproject',
            name='costs_month_9',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='sproject',
            name='end_construction',
            field=models.DateTimeField(blank=True, default='2020-06-20', null=True),
        ),
        migrations.AddField(
            model_name='sproject',
            name='operating_life',
            field=models.IntegerField(default='20'),
        ),
        migrations.AddField(
            model_name='sproject',
            name='start_construction',
            field=models.DateTimeField(blank=True, default='2020-06-20', null=True),
        ),
    ]
