# Generated by Django 4.0.4 on 2022-07-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxPost', '0011_sproject_costs_at_fc_sproject_costs_at_ntp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sproject',
            name='start_construction',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
