# Generated by Django 4.2 on 2023-07-16 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxPost', '0011_project_price_elec_high_y31_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end_construction',
            field=models.DateField(blank=True, default=datetime.date(2022, 12, 31), null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_construction',
            field=models.DateField(blank=True, default=datetime.date(2022, 1, 1), null=True),
        ),
    ]
