# Generated by Django 4.2 on 2023-07-16 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxPost', '0012_alter_project_end_construction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='P99_10y',
            field=models.IntegerField(default='1600'),
        ),
        migrations.AlterField(
            model_name='project',
            name='SHL_margin',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=4),
        ),
        migrations.AlterField(
            model_name='project',
            name='annual_degradation',
            field=models.DecimalField(decimal_places=3, default=0.4, max_digits=5),
        ),
        migrations.AlterField(
            model_name='project',
            name='cash_min',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contract_indexation',
            field=models.DecimalField(decimal_places=2, default=0.02, max_digits=4),
        ),
        migrations.AlterField(
            model_name='project',
            name='contract_indexation_start_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 1, 1), null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='contract_price',
            field=models.DecimalField(decimal_places=2, default=130, max_digits=6),
        ),
        migrations.AlterField(
            model_name='project',
            name='costs_m1',
            field=models.IntegerField(default='200'),
        ),
        migrations.AlterField(
            model_name='project',
            name='costs_m10',
            field=models.IntegerField(default='300'),
        ),
        migrations.AlterField(
            model_name='project',
            name='costs_m11',
            field=models.IntegerField(default='500'),
        ),
        migrations.AlterField(
            model_name='project',
            name='costs_m12',
            field=models.IntegerField(default='600'),
        ),
        migrations.AlterField(
            model_name='project',
            name='costs_m2',
            field=models.IntegerField(default='200'),
        ),
        migrations.AlterField(
            model_name='project',
            name='costs_m3',
            field=models.IntegerField(default='500'),
        ),
        migrations.AlterField(
            model_name='project',
            name='costs_m4',
            field=models.IntegerField(default='300'),
        ),
        migrations.AlterField(
            model_name='project',
            name='costs_m5',
            field=models.IntegerField(default='100'),
        ),
        migrations.AlterField(
            model_name='project',
            name='costs_m6',
            field=models.IntegerField(default='1000'),
        ),
        migrations.AlterField(
            model_name='project',
            name='costs_m7',
            field=models.IntegerField(default='700'),
        ),
        migrations.AlterField(
            model_name='project',
            name='costs_m8',
            field=models.IntegerField(default='600'),
        ),
        migrations.AlterField(
            model_name='project',
            name='costs_m9',
            field=models.IntegerField(default='200'),
        ),
        migrations.AlterField(
            model_name='project',
            name='debt_commitment_fee',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='project',
            name='debt_gearing_max',
            field=models.DecimalField(decimal_places=2, default=80, max_digits=4),
        ),
        migrations.AlterField(
            model_name='project',
            name='debt_reference_rate_buffer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='project',
            name='debt_swap_margin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='project',
            name='debt_swap_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='project',
            name='debt_upfront_fee',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=4),
        ),
        migrations.AlterField(
            model_name='project',
            name='devfee_choice',
            field=models.IntegerField(default='2'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_contract',
            field=models.DateField(blank=True, default=datetime.date(2042, 12, 31), null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='initial_wc',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='project',
            name='operating_life',
            field=models.IntegerField(default='25'),
        ),
        migrations.AlterField(
            model_name='project',
            name='opex',
            field=models.IntegerField(default='50'),
        ),
        migrations.AlterField(
            model_name='project',
            name='opex_indexation',
            field=models.DecimalField(decimal_places=2, default=0.015, max_digits=4),
        ),
        migrations.AlterField(
            model_name='project',
            name='opex_indexation_start_date',
            field=models.DateField(blank=True, default=datetime.date(2024, 1, 1), null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='p50',
            field=models.IntegerField(default='1800'),
        ),
        migrations.AlterField(
            model_name='project',
            name='p90_10y',
            field=models.IntegerField(default='1700'),
        ),
        migrations.AlterField(
            model_name='project',
            name='panels_capacity',
            field=models.IntegerField(default='2500'),
        ),
        migrations.AlterField(
            model_name='project',
            name='price_elec_indexation',
            field=models.DecimalField(decimal_places=2, default=0.02, max_digits=4),
        ),
        migrations.AlterField(
            model_name='project',
            name='price_elec_indexation_start_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 1, 1), null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_contract',
            field=models.DateField(blank=True, default=datetime.date(2023, 1, 1), null=True),
        ),
    ]
