# Generated by Django 4.0.4 on 2022-07-30 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxPost', '0012_remove_sproject_production_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sproject',
            name='costs_at_COD',
        ),
        migrations.RemoveField(
            model_name='sproject',
            name='costs_at_FC',
        ),
        migrations.RemoveField(
            model_name='sproject',
            name='costs_at_NTP',
        ),
    ]
