# Generated by Django 4.2 on 2023-07-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxPost', '0013_alter_project_p99_10y_alter_project_shl_margin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='costs_m11',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='project',
            name='costs_m12',
            field=models.IntegerField(default='500'),
        ),
        migrations.AlterField(
            model_name='project',
            name='costs_m2',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='project',
            name='costs_m5',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='project',
            name='panels_capacity',
            field=models.IntegerField(default='3000'),
        ),
    ]
