# Generated by Django 4.0.4 on 2022-07-30 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxPost', '0013_remove_sproject_costs_at_cod_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SProject',
            new_name='Project',
        ),
    ]
