# Generated by Django 4.2 on 2023-07-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxPost', '0014_alter_project_costs_m11_alter_project_costs_m12_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='debt_gearing_max',
            field=models.DecimalField(decimal_places=2, default=90, max_digits=4),
        ),
    ]
