# Generated by Django 4.2 on 2023-07-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxPost', '0015_alter_project_debt_gearing_max'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='panels_capacity',
            field=models.IntegerField(default='2500'),
        ),
    ]
