# Generated by Django 4.2 on 2023-07-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxPost', '0016_alter_project_panels_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contract_indexation',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='project',
            name='opex_indexation',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='project',
            name='price_elec_indexation',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=4),
        ),
    ]
