# Generated by Django 4.2 on 2023-07-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxPost', '0017_alter_project_contract_indexation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sensi_revenues',
            field=models.DecimalField(decimal_places=0, default=-15, max_digits=3),
        ),
    ]
