# Generated by Django 4.2 on 2023-07-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxPost', '0018_project_sensi_revenues'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sensi_inflation',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=3),
        ),
        migrations.AddField(
            model_name='project',
            name='sensi_opex',
            field=models.DecimalField(decimal_places=0, default=10, max_digits=3),
        ),
    ]
