# Generated by Django 4.2 on 2023-07-26 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxPost', '0019_project_sensi_inflation_project_sensi_opex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='sensi_revenues',
            new_name='sensi_production',
        ),
    ]
