# Generated by Django 4.2 on 2023-08-07 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxPost', '0020_rename_sensi_revenues_project_sensi_production'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='sensi_inflation',
        ),
    ]
