# Generated by Django 4.0.4 on 2022-08-02 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxPost', '0021_project_price_elec_high_y1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='opex_indexation',
            field=models.DecimalField(decimal_places=2, default=0.05, max_digits=4),
        ),
        migrations.AddField(
            model_name='project',
            name='opex_indexation_start_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='contract_price',
            field=models.DecimalField(decimal_places=2, default=58, max_digits=6),
        ),
    ]
