# Generated by Django 4.2 on 2023-10-07 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxPost', '0021_remove_project_sensi_inflation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='sensi_production',
        ),
    ]
