# Generated by Django 4.0.4 on 2022-08-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxPost', '0022_project_opex_indexation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='production_choice',
            field=models.IntegerField(default='2'),
        ),
    ]
