# Generated by Django 4.2 on 2023-10-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxPost', '0022_remove_project_sensi_production'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sensi_production',
            field=models.DecimalField(decimal_places=0, default=-15, max_digits=3),
        ),
    ]
