# Generated by Django 4.2 on 2023-10-07 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxPost', '0023_project_sensi_production'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='sensi_production',
        ),
    ]
