# Generated by Django 4.0.4 on 2022-08-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxPost', '0023_project_production_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='price_elec_choice',
            field=models.IntegerField(default='2'),
        ),
    ]
