# Generated by Django 4.0.4 on 2022-08-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxPost', '0024_project_price_elec_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='debt_commitment_fee',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=4),
        ),
        migrations.AddField(
            model_name='project',
            name='debt_gearing_max',
            field=models.DecimalField(decimal_places=2, default=90, max_digits=4),
        ),
        migrations.AddField(
            model_name='project',
            name='debt_margin',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=4),
        ),
        migrations.AddField(
            model_name='project',
            name='debt_negative_tail',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='project',
            name='debt_reference_rate_buffer',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4),
        ),
        migrations.AddField(
            model_name='project',
            name='debt_swap_margin',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=4),
        ),
        migrations.AddField(
            model_name='project',
            name='debt_swap_rate',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=4),
        ),
        migrations.AddField(
            model_name='project',
            name='debt_target_DSCR',
            field=models.DecimalField(decimal_places=2, default=1.15, max_digits=4),
        ),
        migrations.AddField(
            model_name='project',
            name='debt_tenor',
            field=models.IntegerField(default='20'),
        ),
        migrations.AddField(
            model_name='project',
            name='debt_upfront_fee',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=4),
        ),
    ]
