# Generated by Django 4.2 on 2023-10-07 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxPost', '0025_remove_project_production_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='production_choice',
            field=models.IntegerField(default='2'),
        ),
    ]
