# Generated by Django 4.0.4 on 2022-08-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxPost', '0025_project_debt_commitment_fee_project_debt_gearing_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='corporate_income_tax',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=4),
        ),
    ]
