# Generated by Django 4.0.4 on 2022-08-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxPost', '0026_project_corporate_income_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='country',
            field=models.IntegerField(default='2'),
        ),
        migrations.AddField(
            model_name='project',
            name='technology',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='project',
            name='periodicity',
            field=models.IntegerField(default='6'),
        ),
    ]
