# Generated by Django 4.2 on 2023-10-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxPost', '0027_remove_project_p99_10y'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='P99_10y',
            field=models.IntegerField(default='1600'),
        ),
    ]
