# Generated by Django 4.0.4 on 2022-08-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxPost', '0027_project_country_project_technology_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='country',
            field=models.CharField(default='France', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='technology',
            field=models.CharField(default='Solar', max_length=100),
        ),
    ]
