# Generated by Django 4.2 on 2023-10-07 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxPost', '0028_project_p99_10y'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='production_choice',
        ),
    ]
