# Generated by Django 4.0.4 on 2022-08-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxPost', '0029_alter_project_country_alter_project_technology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='country',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='project',
            name='technology',
            field=models.IntegerField(default=1),
        ),
    ]
