# Generated by Django 4.0.4 on 2022-08-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxPost', '0030_alter_project_country_alter_project_technology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='country',
            field=models.CharField(choices=[('France', 'France'), ('Spain', 'Spain')], max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='technology',
            field=models.CharField(choices=[('Solar', 'Solar'), ('Wind', 'Wind')], max_length=100),
        ),
    ]
