# Generated by Django 4.2 on 2023-10-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxPost', '0034_project_production_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='production_choice',
            field=models.IntegerField(blank=True, default='2', null=True),
        ),
    ]
