# Generated by Django 4.2 on 2023-10-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxPost', '0035_alter_project_production_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='P99_10y',
            field=models.IntegerField(blank=True, default='1600', null=True),
        ),
    ]
