# Generated by Django 4.2 on 2023-10-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxPost', '0036_alter_project_p99_10y'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sensi_inflation',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=3),
        ),
    ]
