# Generated by Django 4.2 on 2023-10-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxPost', '0037_project_sensi_inflation'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sensi_production',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
        ),
    ]
