# Generated by Django 4.2 on 2023-11-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxPost', '0038_project_sensi_production'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='production_choice',
            new_name='debt_production_choice',
        ),
        migrations.RemoveField(
            model_name='project',
            name='P99_10y',
        ),
        migrations.AddField(
            model_name='project',
            name='p75',
            field=models.IntegerField(default='1750'),
        ),
        migrations.AddField(
            model_name='project',
            name='sponsor_price_elec_choice',
            field=models.IntegerField(default='2'),
        ),
        migrations.AddField(
            model_name='project',
            name='sponsor_production_choice',
            field=models.IntegerField(blank=True, default='2', null=True),
        ),
    ]
