# Generated by Django 4.2 on 2023-11-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxPost', '0039_rename_production_choice_project_debt_production_choice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='debt_production_choice',
            new_name='production_choice',
        ),
        migrations.RemoveField(
            model_name='project',
            name='p75',
        ),
        migrations.RemoveField(
            model_name='project',
            name='sponsor_price_elec_choice',
        ),
        migrations.RemoveField(
            model_name='project',
            name='sponsor_production_choice',
        ),
        migrations.AddField(
            model_name='project',
            name='P99_10y',
            field=models.IntegerField(blank=True, default='1600', null=True),
        ),
    ]
