# Generated by Django 4.2 on 2023-11-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxPost', '0040_rename_debt_production_choice_project_production_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='p75',
            field=models.IntegerField(default='1800'),
        ),
    ]
