# Generated by Django 4.2 on 2023-11-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxPost', '0041_project_p75'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sponsor_price_elec_choice',
            field=models.IntegerField(default='2'),
        ),
        migrations.AddField(
            model_name='project',
            name='sponsor_production_choice',
            field=models.IntegerField(default='3'),
        ),
        migrations.AlterField(
            model_name='project',
            name='p75',
            field=models.IntegerField(default='1750'),
        ),
        migrations.AlterField(
            model_name='project',
            name='price_elec_choice',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='project',
            name='production_choice',
            field=models.IntegerField(default='1'),
        ),
    ]
