# Generated by Django 4.2 on 2023-11-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxPost', '0042_project_sponsor_price_elec_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='capacity_per_turbine',
            field=models.IntegerField(default='5'),
        ),
        migrations.AddField(
            model_name='project',
            name='wind_turbine_installed',
            field=models.IntegerField(default='3'),
        ),
    ]
