# Generated by Django 4.2 on 2023-11-17 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxPost', '0043_project_capacity_per_turbine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='timeline_quarters_ceiling',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='annual_degradation',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.4, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='capacity_per_turbine',
            field=models.IntegerField(blank=True, default='2', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='panels_capacity',
            field=models.IntegerField(blank=True, default='2500', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='wind_turbine_installed',
            field=models.IntegerField(blank=True, default='3', null=True),
        ),
    ]
