# Generated by Django 4.2 on 2023-11-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxPost', '0045_project_dev_tax_commune_tax_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='dev_tax_intercommunal_tax',
        ),
        migrations.RemoveField(
            model_name='project',
            name='dev_tax_regional_tax',
        ),
        migrations.AlterField(
            model_name='project',
            name='dev_tax_taxable_base_solar',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=6),
        ),
        migrations.AlterField(
            model_name='project',
            name='dev_tax_taxable_base_wind',
            field=models.DecimalField(decimal_places=2, default=3000, max_digits=6),
        ),
    ]
