# Generated by Django 4.2 on 2023-11-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxPost', '0047_project_commune'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='archeological_tax',
            field=models.DecimalField(decimal_places=2, default=0.04, max_digits=4),
        ),
        migrations.AddField(
            model_name='project',
            name='archeological_tax_base_solar',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=6),
        ),
    ]
