# Generated by Django 4.2 on 2023-11-26 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxPost', '0048_project_archeological_tax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='lease',
            field=models.IntegerField(default='50'),
        ),
        migrations.AddField(
            model_name='project',
            name='lease_indexation',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=4),
        ),
        migrations.AddField(
            model_name='project',
            name='lease_indexation_start_date',
            field=models.DateField(blank=True, default=datetime.date(2024, 1, 1), null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='archeological_tax',
            field=models.DecimalField(decimal_places=2, default=0.4, max_digits=4),
        ),
        migrations.AlterField(
            model_name='project',
            name='archeological_tax_base_solar',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8),
        ),
        migrations.AlterField(
            model_name='project',
            name='technology',
            field=models.CharField(choices=[('Solar - ground-mounted', 'Solar - ground-mounted'), ('Solar - rooftop', 'Solar - rooftop'), ('Solar - floating', 'Solar - floating'), ('Solar - shade structures', 'Solar - shade structures'), ('Wind', 'Wind')], default='Solar', max_length=100),
        ),
    ]
