# Generated by Django 4.2 on 2023-11-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxPost', '0049_project_lease_project_lease_indexation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tfpb_additional_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='project',
            name='tfpb_commune_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='project',
            name='tfpb_department_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='project',
            name='tfpb_mgt_fee_after',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='project',
            name='tfpb_mgt_fee_y2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='project',
            name='tfpb_region_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
