# Generated by Django 4.2 on 2023-11-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxPost', '0050_project_tfpb_additional_tax_project_tfpb_commune_tax_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tfpb_mgt_fee_after',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tfpb_mgt_fee_y2',
        ),
        migrations.AddField(
            model_name='project',
            name='cfe_commune_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='project',
            name='cfe_discount_tax_base',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=4),
        ),
        migrations.AddField(
            model_name='project',
            name='cfe_discount_tax_base_y1',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=4),
        ),
        migrations.AddField(
            model_name='project',
            name='cfe_instal_q1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='project',
            name='cfe_instal_q2',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=4),
        ),
        migrations.AddField(
            model_name='project',
            name='cfe_instal_q3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='project',
            name='cfe_instal_q4',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=4),
        ),
        migrations.AddField(
            model_name='project',
            name='cfe_intercommunal_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='project',
            name='cfe_localCCI_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='project',
            name='cfe_mgt_fee',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=4),
        ),
        migrations.AddField(
            model_name='project',
            name='cfe_specific_eqp_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
