# Generated by Django 4.2 on 2023-12-31 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxPost', '0052_computationresult_alter_project_commune_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='financial_close_check',
            field=models.BooleanField(default=False),
        ),
    ]
