# Generated by Django 4.2 on 2024-01-01 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxPost', '0055_project_discount_factor_valuation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorCaseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_case_result', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('project', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='AjaxPost.project')),
            ],
        ),
    ]
