# Generated by Django 4.2 on 2024-02-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxPost', '0056_sponsorcaseresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contract',
            field=models.CharField(choices=[('FiT', 'FiT'), ('CfD - E16', 'CfD - E16'), ('CfD - E17', 'CfD - E17'), ('CfD - AO', 'CfD - AO'), ('Corporate PPA', 'Corporate PPA')], default='CfD - AO', max_length=100),
        ),
    ]
